- api/Dockerfile
Makes the image only 115mb and makes CVE count 0.
> Change API container base to alpine

- README.md
Fixed few spelling mistakes in README.md
> Spell fix in README.md

- Dockerfile
> move Go to 1.20

- models/llms/ctransformers/requirements.txt
- models/llms/ctransformers/test.py
- models/llms/ctransformers/test_stream.py
- models/llms/stablelm/stablelm.py
- models/llms/stablelm/test_stream.py
- fix bug with stablelm `CompleteStream()` yield output
- fix bug with ctransformers test prompt input
> Bug Fix: Stablelm and ctransformers

- leapfrogai/requirements.txt
- leapfrogai/serve.py
- models/test/repeater/repeater.py
- pyproject.toml
Will push 0.3.3 with this in prep for backend models
> move to asyncio grpc

- models/llms/mpt-7b-chat/Dockerfile
- models/llms/mpt-7b-chat/README.md
- models/llms/mpt-7b-chat/model.py
* Adds default `IMAGE_TAG` tag to support easy docker deployments
* Adds more detailed instructions for deploying the docker container
* Removes commented out code
* Adds async functions for compatibility with the most recent leapfrogai library
> Updates Dockerfile, readme, and modifies model to use latest leapfrogai

- api/models.toml
- docs/getting-started.md
- models/llms/mpt-7b-chat/README.md
- models/speech2text/whisper/Dockerfile
- models/speech2text/whisper/README.md
* Whisper, mpt-7b-chat, and api dockerfiles updated
* Whisper updated to use chainguard images
* README.md files updated for each installation
> Updates README.md files with docker instructions for easy deployments and updates DOCKERFILE's

- .github/workflows/docker-build.yaml
- .github/workflows/docker-publish.yaml
- Makefile
Update Makefile and workflows to no longer build the api image and zarf package as that is now handled by a different repository
> change publish workflow to only trigger on tags

- .github/workflows/docker-build.yaml
- models/llms/ctransformers/main.py
- models/llms/ctransformers/requirements.txt
- models/llms/mpt-7b-chat/requirements.txt
- models/llms/stablelm/requirements.txt
- models/llms/stablelm/stablelm.py
- models/speech2text/whisper/requirements.txt
- models/test/repeater/requirements.txt
- models/text2vec/all-minilm-l6-v2/model.py
- models/text2vec/all-minilm-l6-v2/requirements.txt
update requirements.txt of all models to include current version of leapfrogai==0.3.3
> make included model examples use asyncio when running model

- chart/templates/namespace.yaml
Sets the istio-injection value in the namepsace to enabled to allow for communication with the frontend.
> Enables istio-injection to allow cluster communication

- models/speech2text/whisper/zarf.yaml
> Bumps zarf package version to 0.0.6

- compose/README.md
- compose/docker-compose.yaml
- models/speech2text/whisper/zarf.yaml
* Adds docker-compose file for bringing up whisper, go api, ctransformers, and doug-translate
* Adds readme for bringing applications up and down
* Fixes whisper skeleton version issue
> Adds docker-compose file and readme

- README.md
- website/content/en/docs/local deploy guide/components.md
Updates the status of the backends in the readme, indicating VLLM, instructor-xl, and whisper progress.
> Updates status of the backends in the readme

- .github/workflows/lint.yaml
- .github/workflows/scorecard.yaml
- .pre-commit-config.yaml
- README.md
Add basic workflows for QoL development
> chore(ci): Add pre-commit linting and scorecard workflows

- .github/ISSUE_TEMPLATE/feature_request_ui.md
Feature Request template for UI issues
> New UI Feature Request Template

- .github/workflows/e2e.yaml
- .github/workflows/pytest.yaml
- Makefile
- packages/llama-cpp-python/Dockerfile
- packages/llama-cpp-python/zarf.yaml
- packages/text-embeddings/zarf.yaml
- packages/vllm/Dockerfile
- packages/vllm/zarf.yaml
- packages/whisper/Dockerfile
- packages/whisper/main.py
- packages/whisper/zarf.yaml
- src/leapfrogai_api/backends/openai/types.py
This PR removes various TODO comments from our code.
When relevant, the TODOs have been 'replaced' with GitHub issues.
> chore: cleanup todo comments throughout the codebase

- packages/api/chart/Chart.yaml
- packages/api/chart/values.yaml
- packages/api/zarf.yaml
- packages/llama-cpp-python/chart/Chart.yaml
- packages/llama-cpp-python/chart/values.yaml
- packages/llama-cpp-python/zarf.yaml
- packages/text-embeddings/chart/Chart.yaml
- packages/text-embeddings/chart/values.yaml
- packages/text-embeddings/zarf.yaml
- packages/vllm/chart/Chart.yaml
- packages/vllm/chart/values.yaml
- packages/vllm/zarf.yaml
- packages/whisper/chart/Chart.yaml
- packages/whisper/chart/values.yaml
- packages/whisper/zarf.yaml
- pyproject.toml
- uds-bundles/latest/cpu/uds-bundle.yaml
- uds-bundles/latest/cpu/uds-config.yaml
- uds-bundles/latest/gpu/uds-bundle.yaml
- uds-bundles/latest/gpu/uds-config.yaml
This PR:
- brings all of our version references in line with each other.
- removes unused variables from some of our UDS configs
The updates in this PR should be a great reference point when issue #326 is being worked on.
> chore: Conform version numbers prior to release

- src/leapfrogai_ui/src/lib/components/ChatSidebar.svelte
- src/leapfrogai_ui/src/lib/components/ChatSidebar.test.ts
- src/leapfrogai_ui/src/lib/helpers/dates.test.ts
- src/leapfrogai_ui/src/lib/helpers/dates.ts
closes #360 
Updates the way we categorize conversations in the sidebar.
Ex: 
Today
Yesterday
This Month
March
January
November
Old
> 360 feat(ui): dates

- .github/workflows/e2e-shim.yaml
- .github/workflows/e2e.yaml
- adr/0000-adr-template.md
- adr/0001-vectordb-backend.md
- adr/0003-database.md
Related to #293 
Coauthored by @andrewrisse
> ADR: Database

- .github/workflows/pytest.yaml
- .pre-commit-config.yaml
- README.md
- packages/llama-cpp-python/pyproject.toml
- packages/text-embeddings/pyproject.toml
- packages/vllm/README.md
- packages/vllm/pyproject.toml
- src/leapfrogai_api/config.example.yaml
Adds huggingface_hub as optional dev dependency to VLLM, text-embeddings, and llama-cpp-python.
To install `python -m pip install .[dev]`
> chore: adding huggingface_hub has optional dev dependency

- src/leapfrogai_api/README.md
- src/leapfrogai_api/data/crud_file_bucket.py
- src/leapfrogai_api/data/crud_file_object.py
- src/leapfrogai_api/pyproject.toml
- src/leapfrogai_api/routers/openai/files.py
- src/leapfrogai_api/routers/supabase_session.py
- supabase/.gitignore
- supabase/config.toml
- supabase/migrations/20240422015807_init-files.sql
- tests/pytest/leapfrogai_api/test_api.py
> feat: files endpoints

- src/leapfrogai_ui/src/lib/components/LFTextArea.svelte
- src/leapfrogai_ui/src/routes/(dashboard)/chat/[[conversation_id]]/+page.svelte
closes #445 
see original issue for video of bug
> fix: input resize bug

- .github/workflows/e2e.yaml
- README.md
- tests/e2e/README.md
- uds-bundles/dev/cpu/uds-bundle.yaml
- uds-bundles/dev/gpu/uds-bundle.yaml
- uds-bundles/latest/cpu/uds-bundle.yaml
- uds-bundles/latest/gpu/uds-bundle.yaml
- website/content/en/docs/local deploy guide/quick_start.md
- corrects the order in which Supabase is deployed relative to Zarf packages with dependent SQL migrations
- fixes/adds docs to run new UDS Core 0.22.2 setup
> fix(build): supabase bundle deployment order

- src/leapfrogai_ui/src/routes/api/messages/new/+server.ts
- src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
Removes code that clears chat input when changing threads. This caused some bugs and will be addressed in a separate issue.
> bug: remove input clearing

- src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
- src/leapfrogai_api/routers/openai/requests/thread_run_create_params_request.py
Pass a model_dump of the tool_resources to the validator
Increase the default tokens generated by the tools.
> fix: Hotfix tool resources

- src/leapfrogai_api/backend/helpers.py
- src/leapfrogai_api/routers/openai/assistants.py
Closes: https://github.com/defenseunicorns/leapfrogai/issues/681
> bug(api): Fixes tools issue with modify asssistant

- src/leapfrogai_api/backend/grpc_client.py
- src/leapfrogai_api/backend/helpers.py
- src/leapfrogai_api/backend/types.py
- src/leapfrogai_api/main.py
- src/leapfrogai_api/routers/openai/requests/create_thread_request.py
- src/leapfrogai_api/routers/openai/requests/run_create_params_request.py
Closes https://github.com/defenseunicorns/leapfrogai/issues/565
View the updated docs at the following urls once you've deployed the api: 
* K8s - https://leapfrogai-api.uds.dev/redoc
* Local - [localhost:8080/redoc](http://localhost:8080/redoc)
> chore(docs): Add documentation to types

- Makefile
- pyproject.toml
- src/leapfrogai_api/data/crud_base.py
- tests/make-tests.mk
- tests/mocks/mock_crud.py
- tests/mocks/mock_session.py
- tests/mocks/mock_tables.py
- tests/unit/conftest.py
- tests/unit/leapfrogai_api/conftest.py
- tests/unit/leapfrogai_api/data/test_crud_base.py
- tests/utils/crud_utils.py
Creates mocks for db session
Creates unit testing for CRUDBase features
Current Errors:
Most sad paths fail because we do not properly process empty return types from the database
> (tests) Unit Testing for CRUDBase

- src/leapfrogai_api/backend/rag/document_loader.py
Fixes typo in the mimetype for xls file uploads
> Fixes mimetype for xls files

- src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/+layout.svelte
- src/leapfrogai_ui/src/styles/main.scss
closes #520 
Fixes styling for defense unicorns footer image on small screens
> 520 bug(ui) - defense unicorns badge on small screens

- .gitignore
- package-lock.json
- src/leapfrogai_ui/package-lock.json
- src/leapfrogai_ui/package.json
- src/leapfrogai_ui/tests/helpers/fileHelpers.ts
moves some testing dependencies to dev deps
> fix(ui) move deps to dev deps

- .github/workflows/release.yaml
This change updates the setup-zarf version to fix issues caused when moving the Zarf repository to a new organization.
> Update setup-zarf version

- .github/workflows/e2e.yaml
- README.md
- website/content/en/docs/local deploy guide/quick_start.md
Update to more recent k3d version for stability.
> Update docs to include new k3d-core version

- src/leapfrogai_ui/playwright.config.ts
Allows Playwright e2es to run locally again
> Fix Playwright tests running locally

- packages/whisper/main.py
- packages/whisper/pyproject.toml
- tests/e2e/test_whisper.py
Ensures that all variables are passed down to the actual whisper model
* `language, temperature, prompt`
> chore(whisper): Pass through variables down to whisper

- src/leapfrogai_ui/src/lib/components/LFHeader.svelte
- src/leapfrogai_ui/src/lib/components/LFHeader.test.ts
- src/leapfrogai_ui/tests/logout.test.ts
closes #866 
Deployed on LF-04
https://www.loom.com/share/1bbeb7a3ebd746b2891f44017f0c4be0
> feat(ui): settings/profile header btn re-design

- src/leapfrogai_ui/src/lib/components/LFHeader.svelte
- src/leapfrogai_ui/tests/header.test.ts
- src/leapfrogai_ui/tests/sidebar.test.ts
> bug(ui) - hide menu btn on non chat pages

- src/leapfrogai_ui/src/lib/components/modals/CreateApiKeyModal.test.ts
- src/leapfrogai_ui/src/lib/mocks/api-key-mocks.ts
- src/leapfrogai_ui/src/lib/mocks/svelte.ts
- src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/api-keys.test.ts
- src/leapfrogai_ui/testUtils/fakeData/index.ts
- src/leapfrogai_ui/vitest-setup.ts
This chore improves our mocking setup for Sveltekit stores. It will help when we can resolve this issue:
https://github.com/defenseunicorns/leapfrogai/issues/636
But we are waiting for a response from Sveltekit Superform first.
> chore(ui): improve sveltekit store mocking

- src/leapfrogai_api/backend/grpc_client.py
If we don't batch the requests we run the risk of erroring when the CreateEmbedding stub returns because the response is too large for our gRPC service to handle.
Closes #885
> fix: batch requests to the CreateEmbedding stub

- src/leapfrogai_api/data/crud_vector_content.py
Change was tested locally and is verified to fix the issue #911
> bug(api): Fix issue where only every 100th vector was being stored #911

- src/leapfrogai_ui/src/lib/mocks/file-mocks.ts
- src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
- src/leapfrogai_ui/src/routes/chat/(settings)/file-management/file-management.test.ts
- src/leapfrogai_ui/tests/file-management.test.ts
closes #628 
[LeapfrogAI - File Management - 12 August 2024 - Watch Video](https://www.loom.com/share/93ab9c6c592d4a92aee538b975bd1f1d)
> feat(ui): 628-download-files

- docs/DEVELOPMENT.md
Fix typo in required package
Fixes a typo in the docs pointing to a non-existent library.
Fixes #
Relates to #
> docs: update development.md

- src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
N/A
- Adds handler for empty `file_ids` list when a run on a thread contains an assistant with no files associated with it
Fixes #994
> fix: run on thread containing an assistant without files

- website/content/en/docs/local-deploy-guide/quick_start.md
remove the deploy steps from this section as it's covered in the next step.
> docs(ui): remove bundle deploy steps

- .github/actions/uds-cluster/action.yaml
- .github/workflows/e2e-vllm.yaml
- .github/workflows/label-lint.yaml
* Updates all of the versions so that they match the commit sha and will not cause renovate to fail due to version mismatches.
> chore: updates the versions to match the git commit sha

- adr/0004-rag-eval-toolset.md
- adr/0007-rag-eval-framework.md
Updates the ADRs associated with RAG evals to "ACCEPTED"
N/A
- status updates to 2 ADRs
> docs: update evals adr status
