defenseunicorns/leapfrogai

api/requirements.txt
Think I forgot to add this to the commit when swapping images or it somehow otherwise got removed - this fixes the API server to use python-multipart
=> Add python-multipart

Dockerfile, leapfrog-values.yaml, leapfrogai/Dockerfile, models/llms/mpt-7b-chat/Dockerfile, models/llms/stablelm/Dockerfile
This PR modifies Dockerfiles and updates the leapfrogai image tags to use when building the Zarf package.
- Updates the chainguard image to use the `latest` tag (versioned image tags are no longer supported)
- Update the image tag for leapfrog images
- Update dockerfile for the base image to ensure the `$HOME/app` directory gets created prior to chowing all the directories. (future images will need to be able to use this directory in as non-root user.
=> Modify dockerfiles

docs/adr/0001-vectordb-backend.md
Creates a document for #185 to provide a starting point for determining what vector db will be used with LeapfrogAI.
The initial ADR format is a combination of the following, with some tailoring for this specific issue:
* https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/templates/decision-record-template-by-michael-nygard/index.md
* https://github.com/joelparkerhenderson/architecture-decision-record/tree/main/examples/css-framework
=> Adds initial vector db ADR

api/models.toml, chart/templates/api/configmap.yaml, models/speech2text/whisper/zarf-config.yaml, models/speech2text/whisper/zarf.yaml, weaviate/zarf.yaml
* This replaces all references from whisper-1 to whisper so that all of the configs are using the same names. The Zarf skeleton was previously referencing "whisper" while the toml files in this repo were referencing "whisper-1" causing them to fail when deployed to a k8s cluster.
* Also replaces deprecated variable `###ZARF_PKG_VAR_REPO###` with `###ZARF_PKG_TMPL_REPO###`
=> Changes all the references from whisper-1 to whisper

Makefile, packages/whisper/Dockerfile, packages/whisper/README.md, packages/whisper/chart/Chart.yaml, packages/whisper/chart/templates/NOTES.txt, packages/whisper/chart/templates/_helpers.tpl, packages/whisper/chart/templates/configmap.yaml, packages/whisper/chart/templates/deployment.yaml, packages/whisper/chart/templates/hpa.yaml, packages/whisper/chart/templates/service.yaml, packages/whisper/chart/templates/serviceaccount.yaml, packages/whisper/chart/values.yaml, packages/whisper/main.py, packages/whisper/whisper-values.yaml, packages/whisper/zarf.yaml, pyproject.toml
This PR consolidates the functional bits from the following repositories:
https://github.com/defenseunicorns/leapfrogai-backend-whisper
=> refactor: migrate whisper zarf config to the monorepo

README.md, website/content/en/docs/leapfrogai/tadpole/tadpole-deploy.md, website/content/en/docs/local deploy guide/components.md, website/content/en/docs/local deploy guide/dependencies.md, website/content/en/docs/local deploy guide/deploy.md, website/content/en/docs/local deploy guide/quick_start.md, website/content/en/docs/local deploy guide/requirements.md
Quick PR to update some the documentation:
- Point people to use UDS to deploy LFAI
- Deprecate instructions for k8s deployment that doesn't use UDS
- Minor other doc fixes
The plan is to adjust this documentation (and add more) once #322 gets finalized, but this documentation is up to date at the moment.
=> UDS Documentation Updates

README.md, pyproject.toml
This PR removes the optional-dependencies `api` and `sdk`. All of the libraries listed in these sections are already listed in the default dependencies location which meant nothing new was being introduced.
=> chore: remove redundant optional dependencies within our pyproject.toml

.github/workflows/e2e.yaml
Fixes a typo where the incorrect yaml shorthand was used for the `e2e.yaml` file.
Fixes a logical error when we ignored the wrong directory
=> fix: correct typos in e2e workflow path triggers

.github/workflows/e2e-shim.yaml, .github/workflows/e2e.yaml
Note: Merge this AFTER #376 
---
This shim workflow runs when the real e2e workflow does not run. This allows us to have branch protection rules that expect the e2e workflow to pass. 
The inspiration for this repo is from [this zarf shim workflow](https://github.com/defenseunicorns/zarf/blob/main/.github/workflows/test-e2e-shim.yml)
=> chore: create shim e2e workflow

.github/workflows/pytest.yaml
The pytest workflow runs really quickly and is extremely lightweight. It probably makes sense to always run it to try to catch errors early and not have to worry about creating a 'shim-workflow' so that we can have branch protection rules.
=> chore(ci): always run the pytest workflow

.github/workflows/e2e.yaml, packages/vllm/Dockerfile, packages/vllm/main.py, packages/vllm/scripts/model_download.py
This PR changes the default model that the vLLM container uses.
This PR captures the work completed in [defenseunicorns/leapfrogai-backend-vllm:PR#21](https://github.com/defenseunicorns/leapfrogai-backend-vllm/pull/21) that was not migrated over to the monorepo yet.
=> chore: update vllm to use gptq quanitzed model

packages/text-embeddings/chart/values.yaml, packages/whisper/chart/values.yaml
Fixes #385 
We were overriding the `nvidia.com/gpu` limit but not the request. Because we [only need the limit to be set](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/) this PR removes the request from the values.yaml.
=> bug: remove hardcoded gpu request value

.github/workflows/e2e-shim.yaml, .github/workflows/e2e.yaml
We don't have any e2e tests that test against the LFAI-UI yet, so it doesn't make sense to use runner time when only UI changes are commited.
We should add workflows that test the UI sooner than later though...
=> chore: restrict e2e tests from running on lfai-ui changes

src/leapfrogai_ui/src/routes/(dashboard)/chat/[[conversation_id]]/+page.svelte, src/leapfrogai_ui/src/routes/(dashboard)/chat/[[conversation_id]]/chatpage.test.ts, src/leapfrogai_ui/tests/chat.test.ts, src/leapfrogai_ui/tests/helpers.ts
Carbon applies the iconDescription as a tooltip for buttons that use icons. This label is attached as an aria-label to the svg component within the button, not the actual button. We need a test id to get the buttons for tests, while also ensuring the tooltips are not undefined for the user. I didn't want to put an aria-label on the button as well as the svg, so this solution fixes the tooltips while also ensuring tests pass.
=> fix: send and cancel btn tooltips

src/leapfrogai_ui/src/lib/components/Message.svelte, src/leapfrogai_ui/src/lib/components/Message.test.ts
Small change to show message edit/copy buttons when a message response is being streamed except for on the last message. Including @gregclark-defenseunicorns as approver this time as this change request was missed on PR that delivered this feature.
=> chore: show copy/edit btns for non last message during regen

.github/workflows/e2e.yaml, .github/workflows/lint.yaml, .github/workflows/pytest.yaml, .github/workflows/release.yaml
This PR adds supabase to the release workflow so that an amd64 and arm64 zarf package will be published whenever a tag is pushed to this repo.
This PR also adds `milestoned` as an event trigger to our workflows. This allows us to trigger workflows on PRs that don't normally trigger a workflow (such as when the author is  `github-actions`.
=> Add supabase to release workflow

.github/release-please-config.json, packages/llama-cpp-python/pyproject.toml, packages/repeater/pyproject.toml, packages/repeater/zarf-config.yaml, packages/text-embeddings/pyproject.toml, packages/vllm/pyproject.toml, packages/whisper/pyproject.toml, src/leapfrogai_api/pyproject.toml, src/leapfrogai_sdk/pyproject.toml
We neglected to include `pyproject.toml` files in the release-please instructions. This PR updates the instructions to ensure these files get updated automatically for future releases.
This PR also manually updates the version of the files that were lagging behind.
=> fix: allow release-please to update pyrpoject.toml files

uds-bundles/latest/cpu/uds-bundle.yaml, uds-bundles/latest/gpu/uds-bundle.yaml
There is a typo in the current bundle spec. We are currently using the `path` key to point to an online artifact when we should be using the `repository` key.
=> fix: update 'latest' bundles to reference ui supabase packages

packages/supabase/bitnami-values.yaml, packages/supabase/chart/templates/uds-package.yaml, packages/supabase/zarf.yaml, uds-bundles/dev/cpu/uds-bundle.yaml, uds-bundles/dev/cpu/uds-config.yaml, uds-bundles/dev/gpu/uds-bundle.yaml, uds-bundles/dev/gpu/uds-config.yaml, uds-bundles/latest/cpu/uds-bundle.yaml, uds-bundles/latest/cpu/uds-config.yaml, uds-bundles/latest/gpu/uds-bundle.yaml, uds-bundles/latest/gpu/uds-config.yaml
This PR turns the domain that supabase serves itself on (and access for other operations) into a value that can be templated and set during deploy time.
The old value was hardcoded to `uds.dev` which always redirects to localhost. This value being hardcode meant that deployments would work on your local machines (or when you could modify your `/etc/hosts` files, but would not work when trying to deploy to a different environment behind a different hostname. Now that the values are templates, deployers of the package have more flexibility over which environments they deploy to.
=> chore: Turn supabase domain into a templated value

.github/dependabot.yml
Instead of having three+ PRs failing workflow, now we only need to have one!
=> chore: group 'minor' and 'patch' level npm dependency updates

src/leapfrogai_ui/src/lib/components/ChatSidebar.svelte, src/leapfrogai_ui/src/lib/components/ChatSidebar.test.ts, src/leapfrogai_ui/src/lib/components/ImportExport.svelte, src/leapfrogai_ui/src/lib/components/ImportExport.test.ts, src/leapfrogai_ui/src/lib/components/LFFileUploader.svelte, src/leapfrogai_ui/src/lib/components/LFHeader.svelte, src/leapfrogai_ui/src/lib/components/LFHeader.test.ts, src/leapfrogai_ui/src/lib/stores/threads.ts, src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.server.ts, src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte, src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts, src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/+layout.svelte, src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/assistants-management-page.test.ts, src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+layout.svelte, src/leapfrogai_ui/src/routes/chat/+layout.server.ts, src/leapfrogai_ui/src/routes/chat/+layout.ts, src/leapfrogai_ui/tests/assistants.test.ts, src/leapfrogai_ui/tests/file-management.test.ts, src/leapfrogai_ui/tests/import_export.test.ts
closes #539 
- Add chat link to LF logo that links back to last viewed chat thread (breadcrumbs also link back to last thread)
- Update import/export text
- Remove excess padding in sidebar
- A few test typescript cleanups
- Fixes bug where thread messages wouldn't show without a page refresh when using in app navigation
=> 539 UI enhancements v2

README.md, packages/llama-cpp-python/README.md, packages/repeater/README.md, packages/text-embeddings/README.md, packages/vllm/README.md, packages/whisper/README.md, src/leapfrogai_api/README.md, tests/e2e/README.md, uds-bundles/dev/README.md, website/content/en/docs/local deploy guide/quick_start.md
- Moves local dev instructions out from the root `README.md` and into each packages' respective `README.md`
- Adds zarf deploy instructions to package READMEs
- Removes redundant instructions in some places
- Misc updates to package READMEs
=> chore: Fill in package READMEs and update docs

src/leapfrogai_api/backend/types.py, src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
This should fix the issue with chopping in the UI when using the default model `TheBloke/Synthia-7B-v2.0-GPTQ`. Bumps the default max tokens to 4096.
=> fix(api): bump max tokens to maximum for Synthia-7B to prevent chopping

website/content/en/docs/local deploy guide/quick_start.md
Makes the following changes to the Quick Start guide:
- Links OS requirements
- Lists the default models that get deployed with LFAI
- Lists minimum and recommended system requirements
- Calls out the ability to swap out models if the user has a device with higher system specs
- Addresses confusion about UI and API URLs
=> Update Quick Start for System Recommendations

src/leapfrogai_api/routers/openai/requests/run_create_params_request.py, src/leapfrogai_api/routers/openai/requests/thread_run_create_params_request.py, src/leapfrogai_api/routers/openai/runs.py, tests/integration/api/test_runs.py
Adjust class names from `*CreateParamsRequestBaseRequest` to `*CreateParamsRequest`
=> (chore) Remove redundancy from some class names

uds-bundles/dev/gpu/uds-config.yaml, uds-bundles/latest/gpu/uds-config.yaml, website/content/en/docs/local deploy guide/quick_start.md
Updated uds-config.yaml to default to a single GPU to ease the use of quick starts. This ensures that users with a single GPU can deploy out of the box.
Updated the docs to include a disclaimer about this and instructions to add additional GPU resources.
=> Updating default GPU resources

packages/api/zarf.yaml, packages/supabase/bitnami-values.yaml, packages/supabase/zarf.yaml, packages/ui/chart/ui-values.yaml, packages/ui/zarf.yaml, uds-bundles/dev/cpu/uds-bundle.yaml, uds-bundles/dev/cpu/uds-config.yaml, uds-bundles/dev/gpu/uds-bundle.yaml, uds-bundles/dev/gpu/uds-config.yaml, uds-bundles/latest/cpu/uds-bundle.yaml, uds-bundles/latest/cpu/uds-config.yaml, uds-bundles/latest/gpu/uds-bundle.yaml, uds-bundles/latest/gpu/uds-config.yaml
Some of our packages started to drift and duplicate the variables we used to declaring the domain name to use. This PR standardizes the variables to `DOMAIN` which also matches the name that other teams have been using for their UDS packages. This PR will simplify bundles and configuration.
=> Chore: Standardize package vars relating to domain names

src/leapfrogai_api/data/crud_base.py, tests/mocks/mock_session.py, tests/mocks/mock_tables.py, tests/unit/leapfrogai_api/data/test_crud_base.py, tests/utils/crud_utils.py
CRUD operations will now raise exceptions instead of catching them and returning None.
- Will return None for exceptions that are due to no results from db
Delete function will only return True/False.
=> chore(api): raise exception on CRUD base fails

packages/supabase/bitnami-values-bootstrap.yaml
The `forceRun=true` configuration was causing issues when performing an upgrade of the bitnami Supabase helm chart.
=> fix: disable forceRun for supabase jwt generation

tests/make-tests.mk
=> fix: Make errors when supabase is unavailable

packages/k3d-gpu/plugin/device-plugin-daemonset.yaml
See issue for more details: https://github.com/defenseunicorns/leapfrogai/issues/834
Original fix implemented on:
- Ubuntu 22.04 Desktop (compute-only, and display) with RTX 40 series
- Ubuntu 22.04 Server (compute-only, and display) with H100s
=> fix: k3d gpu deployment on headless and compute-only gpus

packages/whisper/chart/templates/deployment.yaml
The helm template was checking the wrong value to determine if the `GPU_REQUEST` environment variable should be set. We are not seeing `.Values.resources.requests.nvidia.com/gpu`
=> fix: helm template evaluation for whisper GPU_REQUEST envvar

packages/whisper/Dockerfile, packages/whisper/pyproject.toml
* Adds `preprocessor_config.json` to the copy step of the ctranslate2 conversion so that v3 whisper models have their feature dimensions read in properly. Without this there is a runtime error that occurs.
* `weight of size [1280, 128, 3], expected input[1, 80, 3000] to have 128 channels, but got 80 channels instead`
* Adds `openai-whisper` as a dependency to fix a runtime error when running the backend via GPU
* `Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory`
=> fix(whisper): including missing cuda dependencies required for GPU runtimes

packages/supabase/bitnami-values.yaml
The default value in the upstream chart is to set the Kong Service to `LoadBalancer` which is unnecessary for our deployment paradigm. Since we rely on UDS (and the Istio that it configures) for our ingress this PR changes the default value for this service to `ClusterIP`
=> chore: set kong service to default to ClusterIP

.github/workflows/release.yaml
This PR adds a step to the release workflow so that necessary Python libraries are installed. These python libraries are used when certain Zarf packages are built so that they can download the models from huggingface.
=> chore: update release workflow to install necessary python deps

src/leapfrogai_ui/src/lib/components/ImportExport.svelte, src/leapfrogai_ui/src/lib/components/LFSidebar.svelte, src/leapfrogai_ui/src/lib/components/LFTextArea.svelte, src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte, src/leapfrogai_ui/tests/import_export.test.ts, src/leapfrogai_ui/tests/sidebar.test.ts
closes #879 
Fixes chat input box pixel jump
Attempts to fix sidebar squish. I have not been able to replicate this issue or determine what caused it to only happen rarely. This fix sets a fixed width to the sidebar to hopefully prevent it in the future.
Fixes a minor test issue where messages were being sent and their thread deleted too fast resulting in an error in the backend logs. 
Fixes issue where "Importing..." spinner was not reset when there was an error importing conversations
=> bug(ui): chat box jump and sidebar squishing 

packages/api/supabase/migrations/20240808164500_v10.0.0_metadata_defaults.sql
Updates the dbs `message_object` table to disallow null metadata and migrate any existing null metadata
=> fix(api): message metadata default to {}

src/leapfrogai_api/data/crud_message.py, src/leapfrogai_api/routers/openai/requests/create_message_request.py
Fixes `null` metadata in cases where `null` metadata is explicitly trying to be inserted into the db by replacing it before db insert.
=> fix(api) - Defaults to {} when none metadata is supplied

website/content/en/docs/local-deploy-guide/requirements.md
We are seeing more people internally running into issues deploying VLLM with older GPUs that don't have enough VRAM.
=> Update requirements.md with minimum GPU requirements

website/content/en/docs/local-deploy-guide/quick_start.md
This fixes the `cd` command in the quick start docs.
N/A
Modified `website/content/en/docs/local-deploy-guide/quick_start.md` with correct command.
Relates to   #961
=> docs: fixed command on Quick Start page (Building the UDS Bundle) docs

packages/vllm/src/main.py
Fixes exception occurring when the dictionary entry has not been instantiated before being referenced.
Exception:
```
│ leapfrogai-model Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                    │
│ leapfrogai-model   File "/home/leapfrogai/.pyenv/versions/3.11.6/lib/python3.11/asyncio/events.py", line 80, in _run …
```
=> fix(vllm): initializes dictionary entry prior to usage

tests/e2e/conftest.py, tests/e2e/test_llama.py, tests/e2e/test_text_embeddings.py, tests/e2e/test_whisper.py, tests/e2e/utils.py
Test discovery in IDE can fail due to code that runs on dependency resolution. This code makes web requests to retrieve access tokens, but can fail due to a number of reasons. As a result, test discovery will fail and the IDE will not show correct information about your test functions, and will have many errors in the test Output log, making debugging other issues more difficult.
This PR moves OpenAI client into a fixture that will only run once for each module. This will prevent the IDE from throwing errors on discovery.
=> test(e2e): move openai client to fixture

src/leapfrogai_ui/src/hooks.server.ts
When viewing a document from a RAG annotation, the content in the iframe was blocked by CSP.
=> fix(ui): csp prevents iframe content from showing

pyproject.toml
This PR pins the dependencies in the root pyproject.toml. This toml file is used in some of our workflows (such as e2e testing and release building) so it is important to have these deps pinned as we have for our other pyproject.tomls.
=> chore: pin python dependencies in root pyproject

packages/api/chart/templates/api/deployment.yaml, packages/api/chart/templates/migration-job.yaml, packages/llama-cpp-python/chart/templates/deployment.yaml, packages/llama-cpp-python/chart/values.yaml, packages/repeater/chart/values.yaml, packages/supabase/migrationChart/templates/migration-job.yaml, packages/text-embeddings/chart/templates/deployment.yaml, packages/text-embeddings/chart/values.yaml, packages/ui/chart/templates/ui/migration-job.yaml, packages/vllm/chart/templates/deployment.yaml, packages/vllm/chart/values.yaml, packages/whisper/chart/templates/deployment.yaml, packages/whisper/chart/values.yaml
Several (if not all 😬) of our deployments had the `fsGroup` configuration in the wrong place so it wasn't actually applying. This led to an issue where our data-injections were not working when the underlying store was not a PVC provisioned with `local-path` as the StorageClass.
This PR fixes the fsGroup key so that it is in the correct place.
=> fix: correct fsGroup configuration in various deployments

.github/workflows/release.yaml, .github/workflows/tag-for-release.yaml
This PR updates our release workflow so that the `tag-for-release` workflow triggers the `publish` workflow (instead of the `publish` workflow being triggered by a tag push.)
Motivation: When the GitHub Bot would create a new tag in our repository the `on.push.tag` trigger would not actually trigger and a manual tag push was required. This change streamlines our release workflow to not require that middle step.
The trigger logic for this change was heavily inspired (:cough: copied :cough:) from [uds-core/.github/workflows/tag-and-release.yaml](https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/tag-and-release.yaml) and [uds-core/.github/workflows/publish.yaml](https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/publish.yaml)
=> chore: update release workflow trigger type

src/leapfrogai_ui/tests/chat.test.ts
Adds an E2E test for chatting with an assistant without files. 
Also added todo comment for the test above it which can be flaky when our backend is getting an assistant response really fast. 
This test does not yet run in the workflow. It also depends on #995
=> chore(ui): add test for assistant with no files

.github/workflows/e2e-registry1-weekly.yaml, .github/workflows/pytest.yaml
Prevents E2E tests from running on draft PRs.
N/A
- Disables E2E that used paid large runners from running on draft PRs
N/A
=> chore(test): prevent E2E tests from running in draft PRs

bundles/dev/cpu/uds-bundle.yaml, src/leapfrogai_ui/README.md
Small doc update for UI about libreoffice when running locally
=> docs(ui): add note about libreoffice to readme

.github/release-please-config.json
This PR removes the Registry1 Weekly from release-please configuration to fix the failing tag workflow.
Release-please configuration does not gracefully handle files that do not have the identifier for updating versions if they are included in the release-please configuration as a target. The release-please identifier for Registry1 Weekly was removed due to the `v0.12.2` branch not containing the correct refs and code for running the Registry1 weekly test. The commit hash in the Registry1 weekly currently points to a commit after `v0.12.2` so that the Registry1 weekly tests run properly, hence why the release-please identifier was removed from the workflow file. In the future, renovate will automate the Registry1 weekly updates and not release-please.
=> fix: exclude registry1 weekly from release-please

src/leapfrogai_api/pyproject.toml
Langchain <=0.2.12 contains a CVE that has no workaround besides updating the dependency.
Scan Report: https://vat.dso.mil/vat/image?imageName=opensource/defenseunicorns/leapfrogai/api&tag=v0.12.2&branch=master for details.
Vulnerability: [CVE-2024-5998](https://vat.dso.mil/vat/finding?name=CVE-2024-5998)
N/A
- updates langchain to 0.2.12 and langchain-community to 0.2.11
- noted required follow-up changes to be made in cross-stream registry1 image: https://repo1.dso.mil/dsop/opensource/defenseunicorns/leapfrogai/api/-/issues/19#note_2518234
Fixes #1047
Relates to: https://repo1.dso.mil/dsop/opensource/defenseunicorns/leapfrogai/api/-/issues/19
=> chore(api): update langchain to 0.2.12

packages/k3d-gpu/Makefile
This will make it easier to override the distro of UDS core when using the make targets to create a new cluster.
None
* Update UDS core version to 0.26.1 in make target
* UDS_VERSION is now the entire distro/version (i.e. `uds-core-slim-dev:0.27.1`) in Makefile
None
=> chore: variablize uds distro for uds make target

packages/vllm/Dockerfile, src/leapfrogai_api/main.py, src/leapfrogai_api/pyproject.toml, src/leapfrogai_api/utils/config.py, tests/pytest/leapfrogai_api/test_api.py
* Replaces [watchfiles](https://pypi.org/project/watchfiles/) with [watchdog](https://pypi.org/project/watchdog/) to deal with the coredump issue being caused by a combination of `awatch`, `asyncio` and test code that is sensitive to async activity.
* Fixes pipeline issue here: https://github.com/defenseunicorns/leapfrogai/actions/runs/10942995090/job/30381326503?pr=854
* OS: Ubuntu 22.04
* Python: 3.11.10
* Github Runer: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
* Replaces watchfiles with watchdog
=> fix(api, tests): configmap reloading core dump

src/leapfrogai_ui/package-lock.json, src/leapfrogai_ui/package.json
Bumps UI's AI dependency to v3.4.0. Renovate #1064 attempted to do this but only updated the lock file, and not the package.json
=> chore(deps): update dependency ai to v3.4.0

src/leapfrogai_ui/package-lock.json, src/leapfrogai_ui/package.json, src/leapfrogai_ui/src/lib/mocks/chat-mocks.ts, src/leapfrogai_ui/src/routes/api/chat/+server.ts
Removes StreamingTextResponse usage from ai package which was depracted. Also bumps @playwright/test to 1.47.2 due to an issue with running playwright tests in headed mode. This was not working properly after renovate bumped to 1.47.0.
Closes #1095
=> chore(ui): streaming text response deprecated

src/leapfrogai_api/typedef/assistants/assistant_types.py, tests/conformance/test_conformance_assistants.py, tests/utils/client.py
Fixes issue where modifying certain fields on an assistant can also overwrite the intended model for that assistant.
None
Fixes #1156
=> fix(api): make model field optional in ModifyAssistantRequest type

src/leapfrogai_ui/src/lib/components/FileChatActions.svelte
Allows large transcribe and translate messages to be saved to the DB (we should only prevent large user messages)
=> fix(ui): allow large transcribe and translate responses

packages/whisper/Dockerfile
* Removes newlines that were causing the creation of an invalid environment variable entry.
* Resolves issue with failing gpu pod being unable to find the `libcudnn_ops_infer.so` file.
=> fix(whisper): failing gpu pod due to mangled env variable

.github/workflows/nightly-snapshot-release.yaml
There is a typo where the repository is missing a `/` at the end of `/uds/snapshots`, causing the packages to be published to the incorrect namespace.
As a correction to this action, all packages published to the `/uds/snapshots[PACKAGE_NAME]` namespace should be deleted upon the merging of this PR (e.g., [packages/uds/snapshotssupabase](https://github.com/orgs/defenseunicorns/packages/container/package/packages%2Fuds%2Fsnapshotsleapfrogai%2Fsupabase))
- fix for typo that was introduced when variabilizing the namespace for snapshot releases
N/A
=> fix: nightly snapshots repository typo

README.md
Updates README badges to only look at the cron-job (nightly, weekly) workflows run on the `main` branch.
NOTE: since the registry1 workflow was refactored, it technically hasn't run on `main` yet, so hence the `status unknown`. It will run this weekend.
=> fix(docs): cron-job badges should look at main branch workflows only

src/leapfrogai_ui/package-lock.json, src/leapfrogai_ui/package.json, src/leapfrogai_ui/src/lib/components/Message.svelte, src/leapfrogai_ui/tests/assistants.test.ts, src/leapfrogai_ui/tests/rag.test.ts
Bumps @sveltejs/kit to 2.6.2 which resolves CVE-2024-47764 (bumps cookie package version)
Also fixes a couple playwright tests that were not passing after minor style updates.
Skips 3 playwright tests and adds todo. Tests are actually broken, but are for a minor issue that will require deeper investigation. 
Issue for that todo:
https://github.com/defenseunicorns/leapfrogai/issues/1199
=> chore(ui): bump @sveltejs/kit and fix e2es

src/leapfrogai_api/backend/converters.py
Fixes annotations coming back as `file ids` instead of `[1][2][etc.]`
Fixes #
Relates to #
=> fix(api): annotations replacement text contains file ids
